### ISSUE TITLE
client secrets in plain text

### ISSUE THREAD

**Issue by FiveVoltLogic** [broizter/spotifyPlaylistExporter#1]
Heya! Thanks for this script, you've helped me out of a hole.

While using the code, though, It looks like you've left your client ID, secret, and refresh token in the config.ini file.
For safety's sake, I would consider swapping these out for a generic <YOUR CLIENT_SECRET> instead.

Kind Regards,
Will

**Comment by broizter** [comment]
Hey! These are just generated samples that shouldn't lead to anywhere. I was debating if it was more clear to leave fake IDs in there or just leave the values empty. Will rethink my strategy there maybe.

**Comment by FiveVoltLogic** [comment]
Ah, ok. Now I've read in the readme that it says to swap out the examples. My bad. I'd only say that I'm much more used to seeing "YOUR CLIENT_SECRET" rather than an example client secret. It also means that if the user runs the script and gets an error along the lines of "check config.ini", they can see the error staring them in the face.

I'm just trying to get this refresh token now. I have a playlist of 6k+ songs and the spotify to ytmusic playlist converter I'm using doesn't seem to like playlists that big, so I'm trying to split it down into more managable chunks.

**Comment by broizter** [comment]
> It also means that if the user runs the script and gets an error along the lines of "check config.ini", they can see the error staring them in the face.

That's a very good idea! I'll try to implement something like it into the script. I appreciate the feedback!
